### ISSUE TITLE
Formatting Storedprocedure will add blank to !! (concat) 

### ISSUE THREAD

**Issue by ThomasLieser** [IBM/db2forzosdeveloperextension-about#121] opened 2023-12-19 07:49 UTC
In Version 2.1.4 if I format this code

```
    set v_error = -99
	,v_errormsg = 'No such IDSERVER (' !! strip(v_package) !! ', ' !! strip(v_klassenName) !! ', ' !! strip(v_attrName) !! ')'
    ,v_type = 'Unknown';
```
it will result in
```
    set v_error = -99, v_errormsg = 'No such IDSERVER (' ! ! strip(v_package) ! ! ', ' ! ! strip(v_klassenName) ! ! ', ' ! ! strip(v_attrName) ! ! ')'
    , v_type = 'Unknown';
```
Which causes the system to display several error messages as !! is replaced by ! ! which is not recognized as a concat operator.

**Comment by katsoohoo** [comment] 2023-12-21 19:09
Hi @ThomasLieser,

Thanks for reporting this issue. We'll take a look at this.

**Comment by FALLAI-Denis** [comment] 2023-12-22 14:41
Hi,

Please note that the visual rendering of characters, on mainframe and locally, depends on the encoding used. 
The same hexadecimal encoding can be interpreted with different glyphs.

[Expressions with the concatenation operator](https://www.ibm.com/docs/en/db2-for-zos/12?topic=expressions-concatenation-operator), for EBCDIC IBM-037 encoding, use `||` (x'4F4F') sequence, with a tolerance for the `]]` (x'BBBB') sequence and `!!` (x'5A5A') sequence.

With EBCDIC IBM-1147 encoding (what I use), these hexadecimal sequences are rendered differently:
* x4F4F: `!!`
* x5A5A: `§§`
*xBBBB: `||`

The formatting should therefore take into account the encoding used on the mainframe to interpret the character sequences locally, (I think UTF-8), since the local transfer will not produce the same characters depending on the encoding on mainframe.

**Comment by ThomasLieser** [comment] 2023-12-22 17:20
@FALLAI-Denis 
Looks like I didn't explain this properly - sorry - I'm entering two ! and then I apply the Formatter - the code is modified with a blank between the two characters - and marked down as being in error (without deploying it).
I've never had this problem with Datastudio (though that didn't like !! on the start of the line). 

I will check once I'm back in the office and give a better description)

**Comment by FALLAI-Denis** [comment] 2023-12-23 10:53
Hi @ThomasLieser,

The description of the issue is clear: the formatting applied does not recognize the  séquence `!!` and introduces a space between each `!`, probably because formatting only recognizes the sequence `||`. 

The purpose of my comments is to explain that depending on the codepage used on mainframe (and also used by the Db2 system), we can have a different visual rendering of hexadecimal values, on mainframe but also after local transfer and translation to UTF-8 (or ASCII).

The SQL parser that should be the basis of the formatting (tokenization of the SQL code) must therefore take into account the variations introduced by the codepages used on the mainframe.

Perhaps the extension should support a setting for interpreting characters used by SQL statements that have a visual rendering that depends on the mainframe codepage.

**Comment by ThomasLieser** [comment] 2023-12-27 08:37
@FALLAI-Denis  Thanks for your feedback - I have been using Datastudio for years now - always used that way of specifying a concat operator. But it will not be a problem switching over to double pipe symbol.

**Comment by ThomasLieser** [comment] 2023-12-27 09:35
@FALLAI-Denis 
P.S.: as the double pipe works in all tools (QMF Spufi, Datastudio and DB2 Extension) we will just changes the occurences in our code before finally moving to VSCode! 
Thanks again

**Comment by ThomasLieser** [comment] 2023-12-27 09:41
misunderstand on my side - solved

**Comment by FALLAI-Denis** [comment] 2023-12-27 10:11
> P.S.: as the double pipe works in all tools (QMF Spufi, Datastudio and DB2 Extension) we will just changes the occurences in our code before finally moving to VSCode! Thanks again

Hi @ThomasLieser 

Before modifying the code of your procedures, I would advise you to wait for an official response from the team that develops Db2 for z/os developer extension.

For my part I only gave an explanation on the interpretation of hexadecimal values for their visual rendering according to the codepage (ccsid) used.
Concerning the concatenation operator, the recommended hexadecimal value remains x4F4F, which corresponds to the visual `||` in IBM-037 and visual `!!` in IBM-1141. Switch to the visual `||` in IBM-1141 will switch to xBBBB coding, corresponding to a visual `]]` in IBM-037, which is also not recommended.

Managing the interpretation of characters according to the codepage (ccsid) is a recurring problem with Db2, already working only on the mainframe, (hence the recommendation to use the same codepage in the Db2 system and the emulator 3270), but this becomes more complex with EBCDIC and non-EBCDIC conversions.

For information, I encounter the same problem with programs in Rexx language which only consider IBM-037 encoding while I work in IBM-1147, and this poses a problem when it comes to working on these Rexx programs with VS Code (and IBM Z Open Editor).

**Comment by ThomasLieser** [comment] 2023-12-27 16:25
OK, Reopened - waiting for official feedback about !! for concat and ^= for not equal - good to have a workaround though

**Comment by FALLAI-Denis** [comment] 2023-12-27 17:47
Hi @ThomasLieser 

In the end, what is important is to see what is recorded at the Db2 package level in the SYSPACKSTMT catalog table, and possibly at the DBRM level, (but in the case of stored procedures in native SQL there is no DBRM).

In principle, the Db2 catalog tables save information in UTF-8 encoding, I think by applying a conversion from the codepage (ccsid) declared for the single byte EBCDIC.

If as I assume you are working on mainframe with a 3270 terminal emulator and in Db2 with the same EBCDIC IBM-1141 encoding, and you are using `||` sequence for the concatenation operator, then this should work fine because it must be the same conversion that is used by Db2 with `CREATE PROCEDURE` statement and populating the SYSPACKSTMT catalog table and by Db2 for z/OS developer extension to work locally in UTF-8.

**Comment by equalchenbj** [comment] 2024-03-28 22:10
@ThomasLieser !! can be recognized in version 2.1.5. Closing this issue. Feel free to reopen it if you have further questions.

**Closed by equalchenbj** 2024-03-28 22:10 UTC
Labels: bug
