### ISSUE TITLE
Distinguish between input hosts-variables and output hosts-variables

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/db2forzosdeveloperextension-about#29] opened 2021-01-05 15:31 UTC
In an SQL query extracted from a program, like a "select into", some hosts-variables are input data of the query, (where clause), and other hosts-variables are output data of the query , (into clause).
The interface for entering the values of hosts-variables should not list the output hosts-variables (into clause).

See also, in the case of input hosts-variables (update / insert ...), if the indicator hosts-variables must be treated identically to the data hosts-variables, (zone: V_prefix_name on the example below below).
Possibly provide "NULL" checkboxes rather than entering a value in the host-variable indicator.

Example:
![image](https://user-images.githubusercontent.com/63861965/103664744-e2827a80-4f72-11eb-86ce-3ff022eaecbb.png)

**Comment by realkendrickren** [comment] 2021-01-05 19:20
@FALLAI-Denis thanks for reporting this issue. We'll look into this.

**Comment by realkendrickren** [comment] 2021-02-05 17:03
@FALLAI-Denis the fix is now published. Please upgrade and give a try. Closing the issue now.

**Closed by realkendrickren** 2021-02-05 17:03 UTC
Labels: bug

**Comment by FALLAI-Denis** [comment] 2021-02-06 11:44
There is still a problem with the indicator areas:
![db2z003](https://user-images.githubusercontent.com/63861965/107117212-04746300-6879-11eb-8623-8eb3a66a525e.png)

**Comment by FALLAI-Denis** [comment] 2021-02-06 11:47
The "into" clause is not recognized, the query cannot be executed:
![db2z004](https://user-images.githubusercontent.com/63861965/107117251-5cab6500-6879-11eb-8751-70deac104b4e.png)

**Comment by realkendrickren** [comment] 2021-02-23 15:16
@FALLAI-Denis the issue is now fixed in v1.1.0, please upgrade the extension in VSCode and give a try. Thanks a lot for reporting and validating the issue. Let me know if you still hit the issue.
