### ISSUE TITLE
Select ASCII graphic data returns internal error

### ISSUE THREAD

**Issue by pymak7** [IBM/db2forzosdeveloperextension-about#82] opened 2022-04-23 07:58 UTC
## Development environment where the bug occurred

- Db2 Developer Extension version: 1.3.5
- Editor platform
  - [x] Visual Studio Code
  - [ ] Eclipse Theia
- Editor platform version: 1.66.2
- Operating system on which your editor runs (for example, Windows 10 2004 or MacOS Catalina 10.15.7): MacOS Monterey 12.3.1
- Java Version (Run `java -version` and paste the details here): 1.8.0_311
- Db2 for z/OS version (including function level for Db2 12): V13R1M500
- [Log files](https://ibm.github.io/db2forzosdeveloperextension-about/docs/troubleshooting/opening-an-issue-and-providing-logs) attached?: No

## Problem description
Selecting ASCII graphic data prompts this error
<img width="459" alt="image" src="https://user-images.githubusercontent.com/104032169/164885608-ef57e748-f599-4e9d-9455-f3cf1c448941.png">
No additional information is provided by the extension to explain why this error occurs.

Selecting UNICODE graphic data is fine.
<img width="328" alt="image" src="https://user-images.githubusercontent.com/104032169/164885459-b627b5ee-e23b-4778-ba98-65e323a7d1e0.png">

Detailed steps for reproducing the problem:

1. Create a table with an ASCII graphic column
2. Populate the table
3. Select the ASCII graphic column with the Db2 Developer Extension

### Observed behavior

- Internal error

### Expected behavior

- Success with no error

**Comment by katsoohoo** [comment] 2022-04-26 17:56
Hi @pymak7,

Thank you for reporting this issue. We will take a look at it.

**Comment by pymak7** [comment] 2022-05-16 20:53
With `Db2 Developer Extension version: 1.4.0`, I get this error now when I select ASCII graphic data
<img width="572" alt="image" src="https://user-images.githubusercontent.com/104032169/168680575-97d1feae-ff2e-427e-9b50-8edcc1c252c0.png">

**Comment by katsoohoo** [comment] 2022-06-07 15:20
Hi @pymak7,

An update for this issue. We found that `UnsupportedCharsetException: Cp301` is caused by using a Java version that doesn't support this codepage. It seems that [IBM SDK Java 8 was the last IBM-provided Java SDK that supported this codepage](https://www.ibm.com/support/pages/semeru-runtimes-migration-guide).

With IBM SDK Java 8, querying ASCII GRAPHIC data returns the same error as querying EBCDIC GRAPHIC data  `java.io.CharConversionException` (reported in #81).

**Comment by katsoohoo** [comment] 2023-02-24 18:03
Hi @pymak7,

With v2.1.0 release, the extension will display � when characters cannot be converted in the SQL results by default. This behavior can be changed with setting `db2forzosdeveloperextension.db2sqlservice.sQL Results.characterConversion`.

![Screen Shot 2023-02-24 at 10 01 11](https://user-images.githubusercontent.com/5027555/221255426-b0d91c1f-da79-4a18-8676-6b35b5a3d1c5.png)

**Comment by katsoohoo** [comment] 2023-04-15 00:14
I will close this issue since the bug was fixed in v2.1.0.

**Closed by katsoohoo** 2023-04-15 00:14 UTC
Labels: bug
