### ISSUE TITLE
-104: SQLSTATE:42601- Error running native stored procedures on version 0.5.9

### ISSUE THREAD

**Issue by nlopresti** [IBM/db2forzosdeveloperextension-about#32] opened 2021-02-16 19:18 UTC
Since the latest update (0.5.9), all native stored procedures fail upon execution with the following error. 
"DB2 SQL Error: SQLCODE=-104, SQLSTATE=42601, SQLERRMC=FROM;;INTO, DRIVER=4.27.25". 

Our process is to build the sql statement, right click run-all. Drop statements work successfully, the Created Procedure statement fails. 

I have downgraded to 0.5.6 and the issue is resolved. I believe there is a compatibility issue somewhere causing this error to occur. 

If you could please point us in the right direction, we'd greatly appreciate it.

**Comment by realkendrickren** [comment] 2021-02-17 03:44
@nlopresti thanks a lot for reporting the issue. This looks a regression bug. We are looking into this and will keep you updated.

**Comment by nlopresti** [comment] 2021-02-17 16:12
Thank you @realkendrickren , I haven't loaded the sponsor version update yet, but do you think this is a bug in that version as well?

**Comment by realkendrickren** [comment] 2021-02-17 16:33
@nlopresti the sponsor version shouldn't have this issue. This one was introduced after that. Thanks.

**Comment by realkendrickren** [comment] 2021-02-23 15:06
@nlopresti the issue is now fixed in v1.1.0 which we just published a couple mins ago. Please upgrade the extension in VSCode and give a try, let us know if you still hit the issue. 

Thanks again.

**Closed** 2021-02-23 15:07 UTC
Labels: bug

**Comment by nlopresti** [comment] 2021-02-23 18:27
@realkendrickren this is confirmed to be resolved and the new release with the ability to deploy/run the code is working beautifully. Thanks again, I will be informing my team.
