### ISSUE TITLE
Rerunning SQL from the query history

### ISSUE THREAD

**Issue by Rune-Christensen** [IBM/db2forzosdeveloperextension-about#58] opened 2021-09-10 12:09 UTC
As a developer I would like to be able to rerun a SQL from the query history.
And I would like to be able to edit the SQL, and edit the options before running the SQL.
So I don't have to enter variables again, and so I can fix minor bugs easily.

**Comment by Marty850** [comment] 2022-03-17 07:38
Hi,
I noticed that the feature was implemented with version 1.3.4 but it doesn't work on my system. I get the following error :

`Error running command queryHistoryProvider.run: Unable to write file 'd:\Users\myuser\.vscode\extensions\ibm.db2forzosdeveloperextension-1.3.4\tmp\history\2022-03-17T07:29:32.486Z0\vscodeTest.sql' (Unknown (FileSystemError): Error: EINVAL: invalid argument, mkdir 'd:\Users\t02492a\.vscode\extensions\ibm.db2forzosdeveloperextension-1.3.4\tmp\history\2022-03-17T07:29:32.486Z0'). This is likely caused by the extension that contributes queryHistoryProvider.run.`

**Comment by katsoohoo** [comment] 2022-03-18 21:13
Hi @Marty850,

Thanks for reporting the issue. We will take a look at this.

**Comment by katsoohoo** [comment] 2023-02-24 17:52
Hi @Marty850,

We've included a fix in v2.1.0 for running SQL from the query history on Windows. Please let us know if the issue has been fixed.

**Comment by katsoohoo** [comment] 2023-04-15 00:10
I will close this issue since the issues has been resolved in v2.1.0

**Closed by katsoohoo** 2023-04-15 00:10 UTC
Labels: enhancement
