### ISSUE TITLE
Edit of Tuning Connection Profile fails

### ISSUE THREAD

**Issue by markusschaub** [IBM/db2forzosdeveloperextension-about#87] opened 2022-07-18 11:50 UTC
Editing a connection profile to enable ssl connection to the database fails with messages:

_13:28:22.193 T.S ÝDefault Executor-thread-4¨ Ýcom.ibm.db2zos.tuningservice.controller.TsExceptionController¨(exception:200) -- uncaught exceptionERROR 
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 4104_                  

edited the properties:
sslConnection    true
sslTrustStoreLocation    safkeyring://xxxxxxxx/yyyyy_zzz_123456

but if sslTrustStoreLocation is safkeyring://xxxxxxxx/yyyyy_zzz_12345 it works. 
But then the name for the truststore is wrong

**Comment by katsoohoo** [comment] 2022-07-19 16:32
Hi @markusschaub,

Thanks for reporting the issue. We will take a look at this.

**Comment by katsoohoo** [comment] 2022-07-25 18:16
@markusschaub We'd also like the [extension's logs, JDBC trace](https://ibm.github.io/db2forzosdeveloperextension-about/docs/troubleshooting/opening-an-issue-and-providing-logs), and your SAF key ring setup.

To summarize, we'd like the following to help recreate the issue:
* Db2 Developer Extension version
* SQL Tuning Services PTF level
* Extension's logs
* Extension's JDBC trace
* SAF key ring setup

**Comment by markusschaub** [comment] 2022-07-26 07:02
[server_2022-07-26T084804.log](https://github.com/IBM/db2forzosdeveloperextension-about/files/9187287/server_2022-07-26T084804.log)
[client_2022-07-26T064802.log](https://github.com/IBM/db2forzosdeveloperextension-about/files/9187288/client_2022-07-26T064802.log)

uploaded the trace-files. 
Db2 Developer Extension:  v1.4.0
SQL Tuning Services PTF level: June 2022
SAF key ring: STCTCPIP/Web_Client  (a shorter name than first time, but still the same error).

**Comment by katsoohoo** [comment] 2022-08-04 01:35
HI @markusschaub,

Thanks for the logs and information. May we also ask for the [SQL Tuning Services logs](https://www.ibm.com/docs/en/db2-for-zos/13?topic=services-troubleshooting)?

**Comment by markusschaub** [comment] 2022-08-08 11:16
[SQL Tuning Service.log](https://github.com/IBM/db2forzosdeveloperextension-about/files/9281250/SQL.Tuning.Service.log)

uploaded the log (sysout) from the SQL Tuning Service started task.

**Comment by zhaoxq** [comment] 2022-08-09 07:57
Thanks for the log.
Does the trust store sslTrustStoreLocation safkeyring://xxxxxxxx/yyyyy_zzz_123456 work in any JDBC other than SQL Tuning service?

**Comment by markusschaub** [comment] 2022-08-09 12:52
Yes, using keytool -list -keystore safkeyring ... -storetype JCERACFKS is successful:

Keystore type: JCERACFKS
Keystore provider: IBMJCE
...

**Comment by zhaoxq** [comment] 2022-08-10 06:35
Can you please execute the commands and share the result?
bash-4.3$ cd $JAVA_HOME/lib/security
bash-4.3$  cat java.security|grep 'security.provider'

Mins is like this:
```
security.provider.1=com.ibm.jsse2.IBMJSSEProvider2
security.provider.2=com.ibm.crypto.provider.IBMJCE
security.provider.3=com.ibm.security.jgss.IBMJGSSProvider
security.provider.4=com.ibm.security.cert.IBMCertPath
security.provider.5=com.ibm.security.sasl.IBMSASL
security.provider.6=com.ibm.xml.crypto.IBMXMLCryptoProvider
security.provider.7=com.ibm.xml.enc.IBMXMLEncProvider
security.provider.8=com.ibm.security.jgss.mech.spnego.IBMSPNEGO
security.provider.9=sun.security.provider.Sun
policy.provider=sun.security.provider.PolicyFile
```

**Comment by markusschaub** [comment] 2022-08-10 07:47
Mine is this:

security.provider.1=com.ibm.jsse2.IBMJSSEProvider2
security.provider.2=com.ibm.crypto.provider.IBMJCE
security.provider.3=com.ibm.crypto.plus.provider.IBMJCEPlus
security.provider.4=com.ibm.security.jgss.IBMJGSSProvider
security.provider.5=com.ibm.security.cert.IBMCertPath
security.provider.6=com.ibm.security.sasl.IBMSASL
security.provider.7=com.ibm.xml.crypto.IBMXMLCryptoProvider
security.provider.8=com.ibm.xml.enc.IBMXMLEncProvider
security.provider.9=com.ibm.security.jgss.mech.spnego.IBMSPNEGO
security.provider.10=sun.security.provider.Sun
policy.provider=sun.security.provider.PolicyFile

**Comment by zhaoxq** [comment] 2022-08-12 23:50
@markusschaub  this issue is caused by our dependency,  can you please open a skill case from here? https://www.ibm.com/mysupport/ 
The skill case can be sent to: Product: IBM Java for z/OS, Support Mission: SDK Java Technology on z/OS

**Comment by katsoohoo** [comment] 2023-04-19 21:10
Hi @markusschaub,

Were you able to open a case against the product that @zhaoxq mentioned?

**Comment by katsoohoo** [comment] 2023-06-23 17:14
I will close this issue as this is an issue with IBM Java side.

**Closed by katsoohoo** 2023-06-23 17:14 UTC
Labels: bug
