### ISSUE TITLE
SQL Tuning Services Requiring a Profile within IBM Db2 for z/OS Developer Extension after PH60806

### ISSUE THREAD

**Issue by CPaceBMI** [IBM/db2forzosdeveloperextension-about#173] opened 2024-10-25 15:10 UTC
[client_2024-10-25T133137.log](https://github.com/user-attachments/files/17523948/client_2024-10-25T133137.log)
[server_2024-10-25T083141.log](https://github.com/user-attachments/files/17523949/server_2024-10-25T083141.log)
[VSCode_Log_Files.zip](https://github.com/user-attachments/files/17523950/VSCode_Log_Files.zip)
I have been working to get the SQL Tuning Services up and running so that we can use the required IBM Db2 for z/OS Developer Extension under VSCode working with DB2 for z/OS V13R1 allowing us to continue to perform SQL tuning. We have now gotten the TMS Service up and running with the UDFs, grants, binds, and database created for the Tuning Services on our technical Database.

After added the SQL Tuning Services Server to Db2 Developer Edition and then updating the Db2 for z/OS Connection to use the Tuning Services Server and disabling tuning profile, we get the message "No tuning profile is associated with connection connection-name. Source: IBM Db2 for z/OS Developer Extension. Select Tuning profile.

I have validated that we do have PTF UI97373 for APAR PH60806 applied and that is the installation shell that was used to build the TMS Server. I have also been able to use the swagger interface to validate the TMS APIs that from what I have been able to test, sees that the TMS Server is working. From looking at the logs on the TMS Server side, it does not appear to ever be hitting the server.

Any assistance would be greatly appreciated.

## Development environment where the bug occurred

- Db2 Developer Extension version: v2.1.7
- Editor platform
  - [X ] Visual Studio Code
  - [ ] Eclipse Theia
- Editor platform version:  V1.94.0
- Operating system on which your editor runs (for example, Windows 10 2004 or MacOS Catalina 10.15.7): Windows 11 Enterprise
- Java Version (Run `java -version` and paste the details here): 
      java version "1.8.0_144"
      Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
      Java HotSpot(TM) Client VM (build 25.144-b01, mixed mode)
- Db2 for z/OS version (including function level for Db2 12):  V13R1 with Catalog Level M100, Code Level M505, Current Function Level M100
- [Log files]() attached?: Yes

## Problem description

Detailed steps for reproducing the problem:

1. Added SQL Tuning Services Server to Db2 Developer Extension
2. Updated Db2 for z/OS Connection to use the newly defined Tuning Services Server
3. Turned off "Enable tuning profile"
4. Open SQL file and highlighted the SQL to execute
5. Right clicked and selected "Tune selected SQL"

### Observed behavior
Error message "No tuning profile is associated with connection DSNC"
-

### Expected behavior
SQL tuning
-

**Comment by CPaceBMI** [comment] 2024-11-05 19:11
Was wondering if anyone is looking into this?  This is preventing us from moving to DB2 V13 because of development debugging and tuning requirements.

Thanks,

Craig

**Comment by equalchenbj** [comment] 2024-11-05 19:45
Hi Craig, sorry for missing your question. 
I'm not able to access the two log files [client_2024-10-25T133137.log]
[server_2024-10-25T083141.log]. Could you share again or send to me directly kechen@ibm.com? Thanks.

**Comment by equalchenbj** [comment] 2024-12-16 22:45
@CPaceBMI Could you close this issue since the problem is resolved? Thanks.

**Closed** 2024-12-16 23:01 UTC
Labels: bug

**Comment by CPaceBMI** [comment] 2024-12-16 23:03
Issue was a bad AT-TLS configuration file causing it not to change to SSL.
